PY_EXPERIMENTER:
  n_jobs: 1

  Database:
    provider: mysql
    database: priorbai

    table:
      name: all_results

      keyfields:
        run_id: { type: VARCHAR(64), values: ["__AUTO__"] }
        optimizer: { type: VARCHAR(64), values: ["successive_halving", "hyperband"] }
        num_arms: {type: INT, values: [32, 64, 128, 256]}
        benchmark: { type: VARCHAR(255), values: ["lcbench"] }
        kernel: { type: VARCHAR(255), values: ["linear"]}
        use_predicted_y: { type: INT, values: [0,1]}
        use_early_stopping: { type: INT, values: [1]}
        seed: {type: INT, values: [0]}
        prior: { type: VARCHAR(255), values: ["uniform", "rank", "performance", "inverse_rank", "indicator"]}
        performance_prior_std: { type: DOUBLE, values: [0.01] }
        sigma0: { type: DOUBLE, values: [0.01, 0.001, 0.0001]}
        epsilon: {type: DOUBLE, values: [0.01]}
        delta: {type: DOUBLE, values: [0.01,]}

      resultfields:
        T_max: INT
        consumed_budget: DOUBLE
        remaining_arms: INT
        num_epsilon_optimal_arms: INT
        arm_id_selected: INT
        regret: DOUBLE
        epsilon_optimal: INT
        best_arm: INT

    logtables:
      sh_iterations:
          iteration: INT
          num_arms: VARCHAR(20)
          best_arm_included: INT
          budget_spent_so_far: DOUBLE
          N_stop: DOUBLE